include ../makeserver.inc

all:            SingleLine.so

OBJS_Utils=     SingleLine.o  

SingleLine.so: $(OBJS_Utils)
	$(RM) $@
	$(CXX) -shared -fPIC -o $@ $(OBJS_Utils)

clean:
	$(RM) core.* *.so  *.o

debug:
	make DEBUG='-D_DEBUG -g'
