include ../makeserver.inc

all:            DBPool.so

OBJS_Utils=     DBPool.o  

DBPool.so: $(OBJS_Utils)
	$(RM) $@
	$(CXX) -shared -fPIC -o $@ $(OBJS_Utils)

clean:
	$(RM) core.* *.so  *.o

debug:
	make DEBUG='-D_DEBUG -g'
